spring.application.name=ants_ktc
server.port=3333

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://server.aptech.io:3307/ants_ktc
spring.datasource.username=ants_user
spring.datasource.password=ants_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
